# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.5 on 2016-05-19 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.9.5 on 2016-06-20 22:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
>>>>>>> 76519429e155357b138cd7113a3b0b71049b89ba


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 76519429e155357b138cd7113a3b0b71049b89ba
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=250)),
                ('site_type', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('site_slug', models.SlugField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
>>>>>>> 76519429e155357b138cd7113a3b0b71049b89ba
            ],
        ),
    ]
