# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_survey',
            name='site_char',
            field=models.TextField(blank=True, verbose_name='distinguishing site characteristics'),
        ),
    ]
