# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerapoint',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='macroinvertebrates',
            name='num_people',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Number of people sorting/identifying'),
        ),
        migrations.AlterField(
            model_name='macroinvertebrates',
            name='time_spent',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Time spent sorting/identifying'),
        ),
        migrations.AlterField(
            model_name='soil_survey',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='distance from stream (ft)'),
        ),
    ]
