# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0002_auto_20170817_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroinvertebrates',
            name='water_type',
            field=models.CharField(blank=True, choices=[(None, '-----'), ('riff', 'riffle'), ('pool', 'pool')], default=None, max_length=4, verbose_name='water type'),
        ),
    ]
