# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import streamwebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0004_auto_20160520_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, validators=[streamwebs.models.validate_UserProfile_birthdate]),
        ),
    ]
