# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0004_auto_20170831_1428'),
        ('streamwebs', '0003_auto_20170906_1452'),
    ]

    operations = [
    ]
