# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0004_auto_20170831_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipAquaticSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('weather', models.CharField(max_length=20, verbose_name='weather')),
                ('riffle_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of riffles')),
                ('pool_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of pools')),
                ('silt', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='silt')),
                ('sand', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='sand')),
                ('gravel', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='gravel')),
                ('cobble', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='cobble')),
                ('boulders', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='boulders')),
                ('bedrock', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='bedrock')),
                ('small_debris', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='small_debris')),
                ('medium_debris', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='medium_debris')),
                ('large_debris', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='large_debris')),
                ('comments', models.CharField(max_length=250, null=True, verbose_name='comments')),
                ('coniferous_trees', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='coniferous_trees')),
                ('shrubs', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='shrubs')),
                ('small_plants', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='small_plants')),
                ('ferns', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='ferns')),
                ('grasses', models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='grasses')),
                ('species', models.CharField(default=0, max_length=250, null=True, verbose_name='species')),
                ('significance', models.CharField(default=0, max_length=250, null=True, verbose_name='significance to riparian area')),
                ('widlife_type', models.CharField(default=0, max_length=500, null=True, verbose_name='type, species, or track/sign')),
                ('wildlife_comments', models.CharField(default=0, max_length=500, null=True, verbose_name='# or comments')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school')),
            ],
        ),
    ]
