# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0006_auto_20170913_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='deciduous_trees',
            field=models.CharField(choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], default=0, max_length=250, null=True, verbose_name='deciduous_trees'),
        ),
    ]
