# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0006_auto_20170906_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_quality',
            name='date',
        ),
        migrations.AddField(
            model_name='water_quality',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='soil_survey',
            name='soil_type',
            field=models.CharField(blank=True, choices=[(None, '-----'), ('sand', 'Sand'), ('loamy_sand', 'Loamy Sand'), ('silt_loam', 'Silt Loam'), ('loam', 'Loam'), ('clay_loam', 'Clay Loam'), ('light_clay', 'Light Clay'), ('heavy_clay', 'Heavy Clay'), ('n/a', 'N/A'), ('other', 'Other')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='water_quality',
            name='DEQ_dq_level',
            field=models.CharField(blank=True, choices=[(None, '-----'), ('A', 'Level A'), ('B', 'Level B'), ('C', 'Level C'), ('D', 'Level D'), ('E', 'Level E')], default=None, max_length=10, null=True, verbose_name='DEQ data quality level'),
        ),
        migrations.AlterField(
            model_name='water_quality',
            name='air_temp_unit',
            field=models.CharField(choices=[('Fahrenheit', 'Fahrenheit'), ('Celsius', 'Celsius')], default='Fahrenheit', max_length=255, null=True, verbose_name='air temperature units'),
        ),
        migrations.AlterField(
            model_name='water_quality',
            name='water_temp_unit',
            field=models.CharField(choices=[('Fahrenheit', 'Fahrenheit'), ('Celsius', 'Celsius')], default='Fahrenheit', max_length=255, null=True, verbose_name='water temperature units'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='air_temp_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='oxygen_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='pH_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='salt_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='turbid_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='water_temp_tool',
            field=models.CharField(choices=[('N/A', None), ('Manual', 'Manual'), ('Vernier', 'Vernier')], default='N/A', max_length=255, null=True),
        ),
    ]
