# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0007_ripaquaticsurvey_deciduous_trees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school'),
        ),
    ]
