# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0008_auto_20170907_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_survey',
            name='soil_type',
            field=models.CharField(choices=[('sand', 'Sand'), ('loamy_sand', 'Loamy Sand'), ('silt_loam', 'Silt Loam'), ('loam', 'Loam'), ('clay_loam', 'Clay Loam'), ('light_clay', 'Light Clay'), ('heavy_clay', 'Heavy Clay'), ('n/a', 'N/A'), ('other', 'Other')], default=None, max_length=10),
        ),
    ]
