# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0009_auto_20170912_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soil_survey',
            old_name='date',
            new_name='date_time',
        ),
    ]
