# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0009_auto_20170914_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='significance',
            field=models.CharField(max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
    ]
