# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0010_auto_20170913_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canopy_cover',
            name='date_time',
        ),
        migrations.AddField(
            model_name='canopy_cover',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='canopy_cover',
            name='time',
            field=models.TimeField(default=b'12:25'),
        ),
    ]
