# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0011_auto_20170914_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments',
            field=models.CharField(max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='wildlife_type',
            field=models.CharField(max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
    ]
