# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0013_auto_20170913_1447'),
        ('streamwebs', '0007_auto_20170919_1517'),
    ]

    operations = [
    ]
