# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0013_auto_20170915_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='bedrock',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='bedrock'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='boulders',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='boulders'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='cobble',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='cobble'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='gravel',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='gravel'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='large_debris',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='large_debris'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='medium_debris',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='medium_debris'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='sand',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='sand'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='silt',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='silt'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='small_debris',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='small_debris'),
        ),
    ]
