# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0014_auto_20170915_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='coniferous_trees',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='coniferous_trees'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='deciduous_trees',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='deciduous_trees'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='ferns',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='ferns'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='grasses',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='grasses'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='shrubs',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='shrubs'),
        ),
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='small_plants',
            field=models.CharField(blank=True, choices=[('Very Little', 'Very Little'), ('Some', 'Some'), ('A Lot', 'A Lot')], max_length=250, null=True, verbose_name='small_plants'),
        ),
    ]
