# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0015_auto_20170915_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.Site', verbose_name='site'),
        ),
    ]
