# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0014_merge_20170922_0918'),
        ('streamwebs', '0016_ripaquaticsurvey_site'),
    ]

    operations = [
    ]
