# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0017_merge_20170925_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='weather',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='weather'),
        ),
    ]
