# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0018_auto_20170925_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripaquaticsurvey',
            name='school',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school'),
        ),
    ]
