# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 13:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0019_auto_20170927_1222'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ripaquaticsurvey',
            managers=[
                ('test_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
