# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0020_auto_20170928_1341'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ripaquaticsurvey',
            managers=[
            ],
        ),
    ]
