# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0021_auto_20170928_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ripaquaticsurvey',
            name='date',
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time'),
        ),
    ]
