# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0022_auto_20171011_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripaquaticsurvey',
            old_name='significance',
            new_name='significance1',
        ),
        migrations.RenameField(
            model_name='ripaquaticsurvey',
            old_name='species',
            new_name='species1',
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='significance2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='significance3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='significance4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='significance5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='significance6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='significance to riparian area'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='species2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='species3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='species4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='species5',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='species6',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
    ]
