# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0023_auto_20171025_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ripaquaticsurvey',
            old_name='wildlife_comments',
            new_name='wildlife_comments1',
        ),
        migrations.RenameField(
            model_name='ripaquaticsurvey',
            old_name='wildlife_type',
            new_name='wildlife_type1',
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_comments6',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='# or comments'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_type2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_type3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_type4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_type5',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='wildlife_type6',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='type, species, or track/sign'),
        ),
    ]
