# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0024_auto_20171025_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripaquaticsurvey',
            name='stream_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='length of stream'),
        ),
    ]
