# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0025_ripaquaticsurvey_stream_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil_survey',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Field notes'),
        ),
    ]
