# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0032_auto_20171215_1128'),
        ('streamwebs', '0031_auto_20171116_1139'),
    ]

    operations = [
    ]
