# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models

def fix_macro_totals(apps, schema_editor):
    Macroinvertebrates = apps.get_model("streamwebs", "Macroinvertebrates")
    for macro in Macroinvertebrates.objects.all():
        macro.tolerant_total = 0
        
        tolerant = [macro.aquatic_worm, macro.blackfly, macro.leech, macro.midge,
            macro.snail, macro.mosquito_larva]

        # loop thru each array-- if a bug's count is at least one, that bug
        # gets n points towards its category's final score (n = 3 for
        # sensitive, n = 2 for somewhat sensitive, n = 1 for tolerant)
        for count in tolerant:
            if count > 0:
                macro.tolerant_total += 1
        macro.save()

class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0033_merge_20171222_0928'),
    ]

    operations = [
        migrations.RunPython(fix_macro_totals)
    ]
