# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import streamwebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0035_editor_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_survey',
            name='landscape_pos',
            field=models.CharField(choices=[('summit', 'Summit'), ('slope', 'Slope'), ('depression', 'Depression'), ('large_flat', 'Large Flat Area'), ('stream_bank', 'Stream Bank')], default=None, max_length=11, verbose_name='landscape position'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='air_temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='air temperature'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='dissolved_oxygen',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='dissolved oxygen (mg/L)'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='pH',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[streamwebs.models.validate_pH], verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='salinity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='salinity (PSU) PPT'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='turbidity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='turbidity (NTU)'),
        ),
        migrations.AlterField(
            model_name='wq_sample',
            name='water_temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='water temperature'),
        ),
    ]
