# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models

def approve_profiles(apps, schema_editor):
    Profiles = apps.get_model("streamwebs", "UserProfile")

    for profile in Profiles.objects.all():
        profile.approved = True
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('streamwebs', '0036_auto_20180102_1429'),
    ]

    operations = [
        migrations.RunPython(approve_profiles)
    ]
