# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamwebs', '0039_auto_20180125_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('entry_field', models.TextField(verbose_name='journal entry field')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.Site', verbose_name='Stream/Site name')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gallery journal entry',
                'verbose_name_plural': 'gallery journal entries',
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='video description')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time')),
                ('video', models.FileField(null=True, upload_to='gallery_videos/', verbose_name='video')),
                ('thumbnail', models.ImageField(null=True, upload_to='gallery_thumbnails/', verbose_name='thumbnail')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.School', verbose_name='school')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streamwebs.Site', verbose_name='Stream/Site name')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'gallery video',
                'verbose_name_plural': 'gallery videos',
            },
        ),
    ]
