POSTGRES_DB=streamwebs
POSTGRES_USER=postgres_user
POSTGRES_PASSWORD=postgres_pw
PYTHONUNBUFFERED=0
# Drop streamwebs database
# STREAMWEBS_DROP=1
# Only run tests
# STREAMWEBS_TEST=1
# Import CSV data (requires STREAMWEBS_DROP=1)
# STREAMWEBS_IMPORT_DATA=1
